---
title: "Map of Opportunity Countries"
runtime: shiny
output: html_document
---

```{r eruptions, echo=FALSE}
suppressWarnings(library(plyr,warn.conflicts=FALSE,quietly=TRUE))
suppressWarnings(library(dplyr,warn.conflicts=FALSE,quietly=TRUE))
suppressWarnings(library(plotly,warn.conflicts=FALSE,quietly=TRUE))
suppressWarnings(library(RCurl,warn.conflicts=FALSE,quietly=TRUE))
suppressWarnings(library(DT,warn.conflicts=FALSE,quietly=TRUE))

pred2<-read.csv('pred1.csv',stringsAsFactors=FALSE)
pred2<-pred2[,2:ncol(pred2)]
ccodes<-read.csv(textConnection(getURL("http://data.okfn.org/data/core/country-codes/r/country-codes.csv")),stringsAsFactors=FALSE)
data_mapper<-function(CountryPredictions,OPPORTUNITY){
    gchars<-ddply(CountryPredictions,.(OpID),summarise,"charsum"=sum(nchars))
    CountryPredictions<-plyr::join(CountryPredictions,gchars)
    CountryPredictions$weight<-CountryPredictions$nchars/CountryPredictions$charsum
    CountryPredictions<-cbind(CountryPredictions[,1:2],CountryPredictions[,3:c(ncol(CountryPredictions)-3)]*CountryPredictions$weight)
    ftemp<-dplyr::filter(CountryPredictions, OpID%in%OPPORTUNITY)
tframe<-reshape2::melt(colSums(ftemp[,3:ncol(ftemp)],na.rm=TRUE)/sum(ftemp[,3:ncol(ftemp)],na.rm=TRUE))
tframe$countryids<-row.names(tframe)
tframe$ccode2<-plyr::join(data.frame("ISO3166.1.Alpha.2"=tframe$countryids),ccodes)$ISO3166.1.Alpha.3
tframe$nameC<-plyr::join(data.frame("ISO3166.1.Alpha.2"=tframe$countryids),ccodes)$official_name_en
tframe$hover<-paste(tframe$nameC,": ",round(tframe$value*100)/100,sep="")
tframe}
```

```{r echo=FALSE}
inputPanel(selectizeInput("OpporID", label = "Opportunity Number", choices = unique(pred2$OpID),multiple=TRUE, selected=pred2$OpID[1]),
selectInput("projection",label="Map Projection",choices=c('equirectangular','mercator', 'orthographic','natural earth','kavrayskiy7','miller', 'robinson','eckert4','azimuthal equal area','azimuthal equidistant','conic equal area','conic conformal','conic equidistant','gnomonic','stereographic','mollweide','hammer','transverse mercator'),selected='mollweide'))
renderPlotly({
g <- list(showframe = FALSE,showcoastlines = TRUE,projection = list(type = input$projection))
l <- list(color = toRGB("grey"), width = 0.5)
d1<-data_mapper(pred2,input$OpporID)
plot_ly(d1,z=value,hoverinfo="text", locations = ccode2, type = 'choropleth', marker = list(line = l),color = value, colors = 'Blues',text=hover,colorbar = list(title = 'Country Relevance'),source="select") %>% layout(title ="<br>Source:<a href='https://github.com/c4fcm/CLIFF'>CLIFF</a>", geo = g)
})
renderTable({
  eventdata<-event_data("plotly_click", source = "select")$pointNumber+1
  d1<-data_mapper(pred2,input$OpporID)
  rframe<-data.frame("col1"=pred2$OpID[sort.int(pred2[,d1$countryids[eventdata]],decreasing=TRUE,index.return=TRUE)$ix[1:5]])
  colnames(rframe)[1]<-paste("Top 5 Opportunities for", d1$nameC[eventdata])
  rframe})
```
